name: plugin_template
version: 0.0.1
publish_to: none
description: plugin_template description

executables:
  plugin_template:

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  args: ^2.3.1
  ide_plugin:
    git:
      url: https://github.com/flutter-runtime/ide_plugin.git
      ref: main
  analyze_cache:
    git:
      url: https://github.com/flutter-runtime/analyze_cache.git
      ref: main
  process_run: ^0.12.3+2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
